run:
  timeout: 5m
  tests: true
  issues-exit-code: 1

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gocritic
    - revive
    - gosimple
    - gofmt

linters-settings:
  revive:
    confidence: 0.8
    rules:
      - name: exported
        disabled: true
      - name: var-naming
      - name: indent-error-flow
      - name: blank-imports
      - name: unexported-return
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  sort-results: true
