package keys

// KeyAction represents a named action that can be bound to keys.
type KeyAction string

const (
	ActionQuit             KeyAction = "quit"
	ActionHelp             KeyAction = "help"
	ActionFilter           KeyAction = "filter"
	ActionRefresh          KeyAction = "refresh"
	ActionContainerStart   KeyAction = "containerStart"
	ActionContainerStop    KeyAction = "containerStop"
	ActionContainerRestart KeyAction = "containerRestart"
	ActionContainerKill    KeyAction = "containerKill"
	ActionContainerRemove  KeyAction = "containerRemove"
	ActionContainerLogs    KeyAction = "containerLogs"
	ActionContainerExec    KeyAction = "containerExec"
	ActionContainerInspect KeyAction = "containerInspect"
	ActionContainerStats   KeyAction = "containerStats"
	ActionContainerPause   KeyAction = "containerPause"

	// TASK-019 advanced container actions.
	ActionContainerUpdate    KeyAction = "containerUpdate"
	ActionContainerDiff      KeyAction = "containerDiff"
	ActionContainerExport    KeyAction = "containerExport"
	ActionContainerCommit    KeyAction = "containerCommit"
	ActionContainerWait      KeyAction = "containerWait"
	ActionContainerCopy      KeyAction = "containerCopy"
	ActionImagePull          KeyAction = "imagePull"
	ActionImageRemove        KeyAction = "imageRemove"
	ActionImagePrune         KeyAction = "imagePrune"
	ActionImageTag           KeyAction = "imageTag"
	ActionImagePush          KeyAction = "imagePush"
	ActionImageSave          KeyAction = "imageSave"
	ActionImageLoad          KeyAction = "imageLoad"
	ActionVolumeCreate       KeyAction = "volumeCreate"
	ActionVolumePrune        KeyAction = "volumePrune"
	ActionVolumeRemove       KeyAction = "volumeRemove"
	ActionNetworkCreate      KeyAction = "networkCreate"
	ActionNetworkPrune       KeyAction = "networkPrune"
	ActionNetworkRemove      KeyAction = "networkRemove"
	ActionTabNext            KeyAction = "tabNext"
	ActionTabPrev            KeyAction = "tabPrev"
	ActionUp                 KeyAction = "up"
	ActionDown               KeyAction = "down"
	ActionEnter              KeyAction = "enter"
	ActionBack               KeyAction = "back"
	ActionDelete             KeyAction = "delete"
	ActionDetail             KeyAction = "detail"
	ActionSwitchRuntime      KeyAction = "switchRuntime"
	ActionCommand            KeyAction = "command"
	ActionImageHistory       KeyAction = "imageHistory"
	ActionEvents             KeyAction = "events"
	ActionRefreshConnections KeyAction = "refreshConnections"
	ActionActionBar          KeyAction = "actionBar"
	ActionClearFilters       KeyAction = "clearFilters"
	ActionContainerRename    KeyAction = "containerRename"
	ActionContainerTop       KeyAction = "containerTop"
	ActionContainerPort      KeyAction = "containerPort"

	// R08-12: Compose project-level actions.
	ActionComposeProjectStart   KeyAction = "compose_project.start"
	ActionComposeProjectStop    KeyAction = "compose_project.stop"
	ActionComposeProjectRestart KeyAction = "compose_project.restart"
	ActionComposeProjectDown    KeyAction = "compose_project.down"
	ActionComposeProjectLogs    KeyAction = "compose_project.logs"
	ActionComposeProjectTop     KeyAction = "compose_project.top"
	ActionComposeProjectPort    KeyAction = "compose_project.port"
	ActionComposeProjectStats   KeyAction = "compose_project.stats"
	ActionComposeProjectScale   KeyAction = "compose_project.scale"
	ActionComposeProjectPause   KeyAction = "compose_project.pause"
	ActionComposeProjectUnpause KeyAction = "compose_project.unpause"
	ActionComposeProjectKill    KeyAction = "compose_project.kill"
	ActionComposeProjectRm      KeyAction = "compose_project.rm"
	ActionComposeProjectPrune   KeyAction = "compose_project.prune"
	ActionComposeProjectRun      KeyAction = "compose_project.run"
	ActionComposeProjectEvents  KeyAction = "compose_project.events"
	ActionComposeProjectDetail  KeyAction = "compose_project.detail"

	// R08-12: Compose service-level actions.
	ActionComposeServiceRun  KeyAction = "compose_service.run"
	ActionComposeServiceExec KeyAction = "compose_service.exec"
	ActionComposeServiceLogs KeyAction = "compose_service.logs"
)
