package keys

const (
	KeySpace      = " "
	KeySpaceName  = "space"
	KeyCtrlPrefix = "ctrl+"
	KeyEnter      = "enter"
	KeyEsc        = "esc"
	KeyTab        = "tab"
	KeyBackspace  = "backspace"
	KeyPgUp       = "pgup"
	KeyPgDn       = "pgdown"

	KeyUp    = "up"
	KeyDown  = "down"
	KeyLeft  = "left"
	KeyRight = "right"

	KeySlash         = "/"
	KeyQmark         = "?"
	KeyOpenBracket   = "["
	KeyCloseBracket  = "]"

	KeyF1  = "f1"
	KeyF2  = "f2"
	KeyF3  = "f3"
	KeyF4  = "f4"
	KeyF5  = "f5"
	KeyF6  = "f6"
	KeyF7  = "f7"
	KeyF8  = "f8"
	KeyF9  = "f9"
	KeyF10 = "f10"
	KeyF11 = "f11"
	KeyF12 = "f12"

	KeyDigit1 = "1"
	KeyDigit2 = "2"
	KeyDigit3 = "3"
	KeyDigit4 = "4"
	KeyDigit5 = "5"
	KeyDigit6 = "6"
	KeyDigit7 = "7"
	KeyDigit8 = "8"
	KeyDigit9 = "9"

	KeyShiftTab         = "shift+tab"
	KeyCtrlSpace        = "ctrl+space"
	KeyCtrlC            = "ctrl+c"
	KeyCtrlA            = "ctrl+a"
	KeyCtrlD            = "ctrl+d"
	KeyCtrlF            = "ctrl+f"
	KeyCtrlF3           = "ctrl+f3"
	KeyCtrlH            = "ctrl+h"
	KeyCtrlI            = "ctrl+i"
	KeyCtrlJ            = "ctrl+j"
	KeyCtrlK            = "ctrl+k"
	KeyCtrlL            = "ctrl+l"
	KeyCtrlM            = "ctrl+m"
	KeyCtrlS            = "ctrl+s"
	KeyCtrlE            = "ctrl+e"
	KeyCtrlP            = "ctrl+p"
	KeyCtrlB            = "ctrl+b"
	KeyCtrlG            = "ctrl+g"
	KeyCtrlN            = "ctrl+n"
	KeyCtrlQ            = "ctrl+q"
	KeyCtrlR            = "ctrl+r"
	KeyCtrlO            = "ctrl+o"
	KeyCtrlT            = "ctrl+t"
	KeyCtrlU            = "ctrl+u"
	KeyCtrlV            = "ctrl+v"
	KeyCtrlW            = "ctrl+w"
	KeyCtrlX            = "ctrl+x"
	KeyCtrlY            = "ctrl+y"
	KeyCtrlZ            = "ctrl+z"
	KeyCtrlOpenBracket  = "ctrl+["
	KeyCtrlBackslash    = "ctrl+\\"
	KeyCtrlCloseBracket = "ctrl+]"
	KeyCtrlCaret        = "ctrl+^"
	KeyCtrlUnderscore   = "ctrl+_"
	KeyShiftCtrlD       = "shift+ctrl+d"
	KeyShiftCtrlR       = "shift+ctrl+r"
	KeyShiftCtrlE       = "shift+ctrl+e"
	KeyComma            = ","
	KeyDelete           = "delete"
	KeyHome             = "home"
	KeyEnd              = "end"
)

const (
	KeySpace_pretty = KSpace
)

// Backward compat: deprecated _up naming (prefer UPPER in letters.go)
const (
	KeyS_up    = "S"
	KeyR_up    = "R"
	KeyK_up    = "K"
	KeyD_up    = "D"
	KeyE_up    = "E"
	KeyP_up    = "P"
	KeyG_up    = "G"
	KeyY_upper = "Y"
	KeyN_upper = "N"
)
