#!/usr/bin/env just --justfile

gsa:
    GOEXPERIMENT=jsonv2 go install github.com/Zxilly/go-size-analyzer/cmd/gsa@latest
    gsa --web ../dist/docker-tui
    go install github.com/imjasonh/gobinsize@latest
    gobinsize -svg out.svg ../dist/docker-tui